name: Build and Test
on: [push, pull_request]
jobs:
  ubuntu:
    strategy:
      matrix:
          version: ["8.0", "8.1", "8.2"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php-sic extension
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
      - name: phpize
        run: phpize
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: test
        run: |
          make test TESTS="--show-diff"